[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
wasabi_solana = "spicyTHtbmarmUxwFSHYpA8G4uP2nRNq38RReMpoZ9c"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/deploy.json"

[[test.genesis]] # TokenSwap program ID
address = "SwapsVeCiPHMUAtzQWZw7RjsKjgCjhwU55QGu4U1Szw"
program = "tests/deps/spl_token_swap.so"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/deps/token_metadata.so"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/08_strategy-tests/21_strategyWithdraw.ts --require tests/hooks/strategyHook.ts"
