[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
wasabi_solana = "Amxm1TKpMsue3x5KrnAzV9U8Sn7afDQQnmMV9znTfd96"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[[test.genesis]] # TokenSwap program ID
address = "SwapsVeCiPHMUAtzQWZw7RjsKjgCjhwU55QGu4U1Szw"
program = "tests/deps/spl_token_swap.so"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts --require tests/rootHooks.ts"
