[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
wasabi_solana = "DVmp8rZQHYSAo2h2SsXERvd85ks8wNUvfw33jLVWc2DX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts --require tests/rootHooks.ts"
