name: Anchor Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLANA_VERSION: "1.18.22"
  ANCHOR_VERSION: "0.30.1"
  RUST_TOOLCHAIN: "1.79.0"
  AGAVE: "/home/runner/.local/share/agave/target/debug"
  SOLANA_INSTALL_PATH: "/home/runner/.local/share/solana/install/active_release"
  SOLANA_SDK_PATH: "/home/runner/.local/share/solana/install/active_release/bin/solana/sdk"
  SOLANA_BIN_PATH: "/home/runner/.local/share/solana/install/active_release/bin"
  CARGO_HOME: "/home/runner/.cargo"

jobs:
  test:
    name: Run Anchor Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true
          profile: minimal
          components: rustfmt, clippy
          targets: wasm32-unknown-unknown

      - name: Debug Rust Post-Install
        run: |
          echo "Rust version:"
          rustc --version
          echo "Rustup version:"
          rustup --version
          echo "Current toolchain:"
          rustup show active-toolchain
          echo "All toolchains:"
          rustup toolchain list
          echo "Default toolchain:"
          rustup default

      - name: Set Rust Default Version
        run: |
          rustup default ${{ env.RUST_TOOLCHAIN }}
          rustup override set ${{ env.RUST_TOOLCHAIN }}
          echo "After setting default and override:"
          rustc --version
          rustup show active-toolchain

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install Solana
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_VERSION }}/install)"
          echo "${{ env.SOLANA_BIN_PATH }}" >> $GITHUB_PATH
          export PATH="${{ env.SOLANA_BIN_PATH }}:$PATH"
          solana --version
          solana-keygen new --no-bip39-passphrase

      - name: Install Anchor CLI
        run: |
          cargo install --git https://github.com/coral-xyz/anchor --tag v${{ env.ANCHOR_VERSION }} anchor-cli --locked
          
      - name: Install node dependencies
        run: yarn install

      - name: Run tests
        run: |
          echo "Current PATH: $PATH"
          which anchor || echo "anchor not found"
          anchor test
